@startuml

' Установка параметров для уменьшения пустого пространства
skinparam entity {
    BackgroundColor LightBlue
    BorderColor DarkBlue
}
skinparam rectangle {
    BackgroundColor LightCoral
    BorderColor DarkRed
}
skinparam layout {
    HorizontalSpacing 50
    VerticalSpacing 20
}

' Установка направления компоновки
top to bottom direction

' Сущности
entity "users" as u {
  +id : int <<PK>>
  +login : VARCHAR(20)
  +password : VARCHAR(50)
  +type_role : int
}

entity "staff" as s {
  +id : int <<PK>>
  +first_name : VARCHAR(45)
  +second_name : VARCHAR(45)
  +login : VARCHAR(20)
  +email : VARCHAR(30)
  +contact_phone : VARCHAR(45)
  +idpost : int <<FK>>
}

entity "customers" as cu {
  +id : int <<PK>>
  +login : VARCHAR(20)
  +first_name : VARCHAR(45)
  +second_name : VARCHAR(45)
  +email : VARCHAR(30)
  +contact_phone : VARCHAR(45)
  +address : VARCHAR(50)
}

entity "departments" as d {
  +id : int <<PK>>
  +name_department : VARCHAR(70)
}

entity "posts" as p {
  +id : int <<PK>>
  +name_post : VARCHAR(70)
  +iddepartment : int <<FK>>
}

entity "orders" as o {
  +id : int <<PK>>
  +type_order : ENUM('Самовывоз', 'Доставка')
  +status : ENUM('Ожидается подтверждение', 'Отправка со склада', 'В пути', 'Готов к получению', 'Отменён')
  +datetime : TIMESTAMP
  +purchase_price : VARCHAR(45)
  +idcustomer : int <<FK>>
}


' Сущности ниже
entity "garage" as g {
  +id : int <<PK>>
  +type_of_work : VARCHAR(70)
}

entity "inventory" as i {
  +id : int <<PK>>
  +name_inventory : VARCHAR(70)
  +type_inventory : VARCHAR(45)
  +idgarage : int <<FK>>
}

entity "car_brands" as cb {
  +id : int <<PK>>
  +name_brand : VARCHAR(45)
}

entity "garage_car_brands" as gcb {
  +idgarage : int <<FK>>
  +idcar_brands : int <<FK>>
}

entity "suppliers" as sp {
  +id : int <<PK>>
  +name_organization : VARCHAR(70)
  +email : VARCHAR(70)
  +contact_phone : VARCHAR(45)
  +contact_person : VARCHAR(45)
  +address : VARCHAR(45)
}

entity "cars" as c {
  +id : int <<PK>>
  +brand : VARCHAR(45)
  +model : VARCHAR(45)
  +year_production : YEAR(4)
  +VIN_number : VARCHAR(17)
  +purchase_price : VARCHAR(45)
  +condition : JSON
  +idgarage : int <<FK>>
  +idsupplier : int <<FK>>
}

entity "history_operations_with_car" as hoc {
  +id : int <<PK>>
  +type_operation_car : VARCHAR(45)
  +description : JSON
  +datetime : TIMESTAMP
  +idcar : int <<FK>>
}

entity "auto_parts" as ap {
  +id : int <<PK>>
  +name_parts : VARCHAR(45)
  +article : VARCHAR(45)
  +condition : VARCHAR(45)
  +purchase_price : VARCHAR(45)
  +description : JSON
  +idcar : int <<FK>>
  +idgarage : int <<FK>>
}

' Новые сущности
entity "cart" as ct {
  +id : int <<PK>>
  +idcustomer : int <<FK>>
  +type_order : ENUM('Самовывоз', 'Доставка')
}

entity "cart_auto_parts" as cap {
  +idcart : int <<FK>>
  +idautoparts : int <<FK>>
}

' Связи
s ||--o{ g : "работает в"
g ||--o{ i : "содержит"
g ||--o{ c : "содержит"
cb ||--o{ gcb : "включает"
g ||--o{ gcb : "содержит"
sp ||--o{ c : "поставляет"
c ||--o{ hoc : "логирует"
cu ||--o{ o : "размещает"
o ||--o{ ap : "содержит"

' Новые связи
c ||--o{ ap : "имеет"
cu ||--o{ d : "принадлежит"

' Связи для новых сущностей
cu ||--o{ ct : "размещает"
ct ||--o{ cap : "содержит"
ap ||--o{ cap : "включает"

d ||--o{ p : "содержит"

@enduml